### PR TITLE
Sector Analysis and Size Distribution Changes

### PR DESCRIPTION
**Pull request by iroreilly**
David, 

I added the ability to have different grids for the input data, so far only for the HREFv2, as well as the training period size distribution for the regression step. Also, I added the ability to output subplots of each member for analysis purposes in the future.

-Amanda

### CODE REVIEW

**Comment by djgagne** [comment]
@alburke The continuous integration check failed because the program could not import pyresample. Please add the library to the requires list in setup.py and commit the changes.

**Comment by iroreilly** [comment]
I deleted the pyresample and griddata imports because I ended up not using them.

-Amanda

**Comment by iroreilly** [comment]
@djgagne I fixed the lines of code that caused the merging to fail, specifically adding the map_file argument under the ModelOutput class, rather than the load_data function.

**Comment by djgagne** [comment]
@alburke Thank you for fixing the map_file issue. Everything else looks good, so I am going to go ahead and merge.

**Pull request merged**
