### PR TITLE
Replaced DateTimeIndex method with pd.date_range

### PR DESCRIPTION
**Pull request by ahijevyc**
FutureWarning: Creating a DatetimeIndex by passing range endpoints is
deprecated.  Use `pandas.date_range` instead

### CODE REVIEW

**Comment by ahijevyc** [comment]
Does this mean I added a bug?
It looks more like conda is arguing with itself about whether it needs the setuptools module.

**Comment by djgagne** [comment]
There is a conda build error. I am going to submit another pull request shortly to fix it and other issues.

**Comment by djgagne** [comment]
Merge the latest master branch with yours, and it should build properly.

**Comment by ahijevyc** [comment]
Done

**Pull request merged**
